/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module fa_checker_1 (
    input [2:0] counter_val,
    input [0:0] c0,
    input [0:0] s,
    output reg [1:0] addResult,
    output reg [0:0] checkResult
  );
  
  
  
  always @* begin
    addResult = counter_val[0+0-:1] + counter_val[1+0-:1] + counter_val[2+0-:1];
    checkResult = ((counter_val[0+0-:1] ^ counter_val[1+0-:1] ^ counter_val[2+0-:1]) ~^ s) & ((counter_val[0+0-:1] & counter_val[1+0-:1] | counter_val[1+0-:1] & counter_val[2+0-:1] | counter_val[0+0-:1] & counter_val[2+0-:1]) ~^ c0);
  end
endmodule
