/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module full_adder_checker_1 (
    input [0:0] a,
    input [0:0] b,
    input [0:0] cin,
    input [0:0] c0,
    input [0:0] s,
    output reg [1:0] addResult,
    output reg [0:0] checkResult
  );
  
  
  
  always @* begin
    addResult = a + b + cin;
    checkResult = ((a ^ b ^ cin) ~^ s) & ((a & b | b & cin | a & cin) ~^ c0);
  end
endmodule
